### ISSUE TITLE
[vne_ege] Реализовать много шариков.

### ISSUE THREAD

**Issue by tkhirianov** [tkhirianov/foxford_2018#2]
Сейчас в программе один single_ball.
Нужно хранить не один шарик, а **список шариков**.

**Comment by tkhirianov** [comment]
Планирую удалить глобальную переменную `single_ball` и сделать глобальный список `balls`.

**Comment by tkhirianov** [comment]
Коллеги, @solaris-ventus @Astrid-and-Stormy , уже скоро всё починю.

**Comment by Astrid-and-Stormy** [comment]
@tkhirianov Это радует. А то все сроки горят.

**Comment by tkhirianov** [comment]
Починил в  999fa49
